# python3 twitter_data_ingestion.py "(saudi vision 2030) OR (Saudi Arabia's Vision 2030) OR #saudivision2030 OR #vision2030 OR #saudi_vision_2030"
# python3 twitter_data_ingestion.py "(Future Investment Initiative) OR #FutureInvestmentInitiative"
# python3 twitter_data_ingestion.py "(Saudi and World bank) OR #InvestSaudi OR #SME OR #future_strategy"
# python3 twitter_data_ingestion.py "(National Transformation Program) OR #SaudiArabia"
# python3 twitter_data_ingestion.py "(Saudi and World Economic Forum)"
# python3 twitter_data_ingestion.py "(Saudi Council of ministers)"
# python3 twitter_data_ingestion.py "(Saudi Arabia General Investment Authority) OR #InvestSaudi OR #General_Investments_Authority OR #investments"
# python3 twitter_data_ingestion.py "(Saudi GDP ) OR (Saudi IMF)"
# python3 twitter_data_ingestion.py "(Davos in the Desert)"
python twitter_data_ingestion.py "#SDGs"