python3 bbc-report.1.py bbc "Davos in the Desert" "analysed_Davos in the Desertbbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Arabia" "analysed_bbc-newsSaudi Arabia.json"
python3 bbc-report.1.py bbc "Economy of Saudi Arabia" "analysed_Economy of Saudi Arabiabbc-news20191204.json"
python3 bbc-report.1.py bbc "Future Investment Initiative" "analysed_Future Investment Initiative bbc-news20191204.json"
python3 bbc-report.1.py bbc "Mohammad bin Salman" "analysed_Mohammad bin Salmanbbc-news20191204.json"
python3 bbc-report.1.py bbc "National Transformation Program" "analysed_National Transformation Programbbc-news20191204.json"
python3 bbc-report.1.py bbc "National" "analysed_Nationalbbc-news20191204.json"
python3 bbc-report.1.py bbc "Public Investment Fund (PIF)" "analysed_Public Investment Fund (PIF) bbc-news20191204.json"
python3 bbc-report.1.py bbc "Red Sea luxury resort" "analysed_Red Sea luxury resortbbc-news20191204.json"
python3 bbc-report.1.py bbc "SAGIA" "analysed_SAGIAbbc-news20191204.json"
python3 bbc-report.1.py bbc "SAMA" "analysed_SAMA bbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi & World Economic Forum" "analysed_Saudi & World Economic Forumbbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi & World bank" "analysed_Saudi & World bank  bbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Arabia General Authority for Entertainment" "analysed_Saudi Arabia General Authority for Entertainmentbbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Arabia General Investment Authority" "analysed_Saudi Arabia General Investment Authority bbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Arabian Monetary Authority" "analysed_Saudi Arabian Monetary Authoritybbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Vision 2030" "analysed_Saudi Arabia’s Vision 2030bbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Council of ministers" "analysed_Saudi Council of ministers bbc-news20191204.json"
python3 bbc-report.1.py bbc "Mohammad bin Salman" "analysed_Saudi Crown Prince Mohammad bin Salmanbbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi GDP" "analysed_Saudi GDP bbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi IMF" "analysed_Saudi IMFbbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi Vision 2030" "analysed_Saudi Vision 2030bbc-news20191204.json"
python3 bbc-report.1.py bbc "Saudi" "analysed_Saudibbc-news20191204.json"