service: lmb-use1-3

plugins:
  - serverless-python-requirements

package:

  exclude:
    - README.md

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: ${opt:stage, ''}
  memorySize: 128
  timeout: 900
  
# Lambda function's IAM Role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:FilterLogEvents"
        - "logs:CreateLogStream"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
        - "sqs:SendMessage"
      Resource: "*"
#Lambda function   
functions:
  report:
    handler: twitter_report.lambda_handler
    reservedConcurrency: 2
    events:
      - sqs: "arn:aws:sqs:us-east-1:069653090426:sqs-use1-twitter-report-generation"
